/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Estoque;
import model.EstoqueDAO;
import services.DB;

/**
 *
 * @author Marquinhos
 */
public class EditarEstoque extends javax.swing.JFrame {

    /**
     * Creates new form EditarEstoque
     */
    public EditarEstoque() {
        initComponents();
        updateTabela();
    }
    
    public void updateTabela(){
        EstoqueDAO edao = new EstoqueDAO();
        ArrayList<Estoque> lista = edao.lista();
        DefaultTableModel model = (DefaultTableModel)Tabela.getModel();
        Object[] linha = new Object[12];
        for(int i = 0; i<lista.size();i++){
            linha[0]=lista.get(i).getCod();
            linha[1]=lista.get(i).getNome();
            linha[2]=lista.get(i).getNcientifico();
            linha[3]=lista.get(i).getFamilia();
            linha[4]=lista.get(i).getOrigem();
            linha[5]=lista.get(i).getPorte();
            linha[6]=lista.get(i).getDisplantio();
            linha[7]=lista.get(i).getTamcova();
            linha[8]=lista.get(i).getCor();
            linha[9]=lista.get(i).getFloracao();
            linha[10]=lista.get(i).getQtd();
            linha[11]=lista.get(i).getPreco();
            model.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "nome", "nome cientifico", "familia", "origem", "porte", "distancia plantio", "tamanho cova", "cor", "floracao", "qtd", "preco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(600, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btSalvar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btnAdd))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        // TODO add your handling code here:

        
    }//GEN-LAST:event_TabelaMouseClicked

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        DB bd = new DB();
//        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        int linhas = Tabela.getRowCount();
        String sql = "UPDATE [dbo].[estoque] "
                + "SET [nome_planta] = ?, "
                + "[ncientifico_planta] = ?, "
                + "[familia_planta] = ?, "
                + "[origem_planta] = ?, "
                + "[porte_planta] = ?, "
                + "[displantio_planta] = ?, "
                + "[tamcova_planta] = ?, "
                + "[cor_planta] = ?, "
                + "[floracao_planta] = ?, "
                + "[qtdestoque_planta] = ?, "
                + "[preco_planta] = ? "
                + "WHERE [cod_planta] =?";
        bd.getConnection();
        try{
            for(int i = 0; i< linhas; i++){
                bd.st = bd.con.prepareStatement(sql);
                bd.st.setString(1, Tabela.getValueAt(i, 1).toString());
                bd.st.setString(2, Tabela.getValueAt(i, 2).toString());
                bd.st.setString(3, Tabela.getValueAt(i, 3).toString());
                bd.st.setString(4, Tabela.getValueAt(i, 4).toString());
                bd.st.setFloat(5, Float.parseFloat(Tabela.getValueAt(i, 5).toString()));
                bd.st.setFloat(6, Float.parseFloat(Tabela.getValueAt(i, 6).toString()));
                bd.st.setFloat(7, Float.parseFloat(Tabela.getValueAt(i, 7).toString()));
                bd.st.setString(8, Tabela.getValueAt(i, 8).toString());
                bd.st.setString(9, Tabela.getValueAt(i, 9).toString());
                bd.st.setInt(10, Integer.parseInt(Tabela.getValueAt(i, 10).toString()));
                bd.st.setFloat(11, Float.parseFloat(Tabela.getValueAt(i, 11).toString()));
                bd.st.setInt(12, Integer.parseInt(Tabela.getValueAt(i, 0).toString()));
                bd.st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Update realizado com sucesso");
            }
        }catch(HeadlessException | SQLException | NullPointerException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }finally{
            bd.close();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new AddEstoque().setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
